stages:
  - build

variables:
  # Задайте змінні, якщо потрібно

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_frontend:
  stage: build
  script:
    - cd frontend
    - docker build -t newimage/frontend:tag1 .
    
