stages:
  - build

test_docker_version:
  stage: build 
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - cd frontend 
    - ls -la 
    - docker build -t frontenddockerimage . 
    - docker images
    - docker login -u urikblack2001 -p UrikBLack@2001 urikblack2001
    - docker tag frontendDockerImage:latest urikblack2001/frontend/frontendDockerImage:latest
    - docker push urikblack2001/frontend/frontendDockerImage:latest
