.cicd_template:

    image: docker:19.03.12
    services:
        - docker:19.03.12-dind

    variables:
        IMAGE_NAME: "IMG_NAME"
        FILE_PATH: "PATH_TO_FILE"
        VERSION: "latest"
    script:
        - echo "start build"
        - docker build -t $CI_REGISTRY_IMAGE/${IMAGE_NAME}:${VERSION} ./${FILE_PATH}
        - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
        - docker push $CI_REGISTRY_IMAGE/${IMAGE_NAME}:${VERSION}

stages:
    - build 


front-build:
    stage: build
    extends: .cicd_template
    variables:
        IMAGE_NAME: "frontend-img"
        FILE_PATH: "frontend"
        VERSION: "latest"


log-msg-proc-build:
    stage: build
    extends: .cicd_template
    variables:
        IMAGE_NAME: "log-img"
        FILE_PATH: "log-message-processor"
        VERSION: "latest"

todos-build:
    stage: build
    extends: .cicd_template
    variables:
        IMAGE_NAME: "todos-img"
        FILE_PATH: "todos-api"
        VERSION: "latest"

auth-build:
    stage: build
    extends: .cicd_template
    variables:
        IMAGE_NAME: "auth-img"
        FILE_PATH: "auth-api"
        VERSION: "latest"


users-api-build:
    stage: build
    extends: .cicd_template
    variables:
        IMAGE_NAME: "users-img"
        FILE_PATH: "users-api"
        VERSION: "latest"