.cicd_config_template:

    image: docker:19.03.12
    services:
        - docker:19.03.12-dind

stages:
    - build 

front-build:
    stage: build
    extends: .cicd_config_template
    variables:
        IMAGE_NAME: "frontend-img"
        FILE_PATH: "frontend"
        VERSION: "latest"


