stages:
  - build

test_docker_version:
  stage: build 
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - cd frontend 
    - ls -la 
    - docker build -t frontenddockerimage . 
    - docker images
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag frontenddockerimage:latest $CI_REGISTRY_IMAGE/frontend/frontenddockerimage:latest
    - docker push $CI_REGISTRY_IMAGE/frontend/frontenddockerimage:latest
