stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - export DOCKER_CLI_ACI=1
  - export DOCKER_CONTENT_TRUST=0
  - apt-get update -qy
  - apt-get install -y docker.io
  - docker info

build_frontend:
  stage: build
  script:
    - cd frontend
    - ls