stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build_frontend:
  stage: build
  script:
    - cd frontend
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
